version: "3.1"

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production

  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/shop?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - "8081:8081"
  
  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - target: 5432
        published: ${POSTGRES_PORT:-5432}
        protocol: tcp
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

  backend:
    build:
      context: backend/
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - postgres
    volumes:
      - ./backend:/app/backend
    user: "1000:1000"

  frontend:
    build:
      context: frontend/
    ports:
      - "3000:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
    user: "1000:1000"

volumes:
    mongodb_data_container: {}
    postgres_data: {}
    